language:
  - minimal

os:
  - linux

sudo:
  - false

dist:
  - trusty

addons:
  apt:
    packages:
      - python3-pip

install:
  - uname -a

  - echo ${PATH}

  - which python3
  - python3 --version

  - which g++
  - g++ --version

  - which clang++
  - clang++ --version

  - which pip3
  - pip3 --version

  - pip3 install --user requests

script:
  - echo "OK"
