language:
  - cpp

os:
  - linux

sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3-pip
      - g++-7

install:
  - uname -a

  - echo ${PATH}

  - which python3
  - python3 --version

  - which g++-7
  - g++-7 --version

  - which clang++
  - clang++ --version

  - which pip3
  - pip3 --version

  - pip3 install --user requests

script:
  - echo "OK"
